name = "TVModels"
uuid = "8a9d810c-6e40-4c7e-99d9-27ac57eb454c"
authors = ["Bohdan Hukovych"]
version = "0.1.0"

[compat]
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
